### ISSUE TITLE
微分求得的速度很容易超过安全限速

### ISSUE THREAD

**Issue by siulamlu** [SheldonLoveCoding/KUKA_AdmittanceControl#1]
博主你好，请问一下，在您的文档中  “基于位置轨迹的导纳控制”：

人腕关节的移动可能会比较快，那么微分求得的速度很容易超过安全限速。

为什么根据这句话把加速度项删掉了呀？

**Comment by SheldonLoveCoding** [comment]
同学您好！

是这样的，我的项目中传感器只能给出腕关节的偏转角度，也就是当前腕关节的位置信息；想要得到速度的话，就需要对位置信息进行微分[d(t) - d(t-1)]得到 v(t)；那么同样的道理，得到加速度就需要进一步对速度进行微分 a(t) = v(t) - v(t-1)；但是由于我们这个项目中，腕关节移动是比较快的，所以微分得到的速度和加速度 都有可能导致机械臂末端移动过快。然而KUKA机械臂的关节移动速度都是有安全限幅的，超速之后就容易导致机器人“紧急停车”，因此就把阻抗模型中的加速度项删掉了，其实主要原因是我们得到的加速度项并不安全。

这是我的想法哈，有问题咱们继续交流。
祝一切顺利！
