### ISSUE TITLE
代码执行报错

### ISSUE THREAD

**Issue by yaofulan** [SheldonLoveCoding/KUKA_AdmittanceControl#2]
错误使用 KST/net_establishConnection
Connection could not be establised, script aborted

出错 KUKA_EffPosControl (第 23 行)
flag=iiwa.net_establishConnection();

博主您好，我直接运行源代码出现报错，是不是机械臂的ip地址没正确呀，“ip='172.31.1.147'; % The IP of the controller”  是要修改这行语句嘛，我改成电脑自身的ip地址也不行，但是我又不知道机械臂的ip

**Comment by SheldonLoveCoding** [comment]
同学你好，机械臂的IP地址需要根据自己的机械臂来修改的。一般来说你可以从KUKA的示教板上找到KUKA的IP地址。

**Comment by yaofulan** [comment]
噢噢，谢谢，这个示教板在哪呀



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SheldonLoveCoding ***@***.***&gt;
发送时间: 2024年3月5日 16:05
收件人: SheldonLoveCoding/KUKA_AdmittanceControl ***@***.***&gt;
抄送: yaofulan ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [SheldonLoveCoding/KUKA_AdmittanceControl] 代码执行报错 (Issue #2)





 
同学你好，机械臂的IP地址需要根据自己的机械臂来修改的。一般来说你可以从KUKA的示教板上找到KUKA的IP地址。

**Comment by SheldonLoveCoding** [comment]
示教板就是和kuka一起出厂生产的控制面板，和机械臂是有线连接的，所有的协作机械臂都有示教板。基于KST连接KUKA你可以从这个连接中找到视频教程。https://www.youtube.com/playlist?list=PLz558OYgHuZd-Gc2-OryITKEXefAmrvae

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月05日 16:07 |
| 收件人 | SheldonLoveCoding/KUKA_AdmittanceControl ***@***.***> |
| 抄送人 | SheldonLoveCoding ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [SheldonLoveCoding/KUKA_AdmittanceControl] 代码执行报错 (Issue #2) |

噢噢，谢谢，这个示教板在哪呀



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SheldonLoveCoding ***@***.***&gt;
发送时间: 2024年3月5日 16:05
收件人: SheldonLoveCoding/KUKA_AdmittanceControl ***@***.***&gt;
抄送: yaofulan ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [SheldonLoveCoding/KUKA_AdmittanceControl] 代码执行报错 (Issue #2)






同学你好，机械臂的IP地址需要根据自己的机械臂来修改的。一般来说你可以从KUKA的示教板上找到KUKA的IP地址。

**Comment by yaofulan** [comment]
噢噢，是控制真实的机械臂呀，我以为是纯matlab仿真，谢谢博主



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SheldonLoveCoding ***@***.***&gt;
发送时间: 2024年3月5日 16:14
收件人: SheldonLoveCoding/KUKA_AdmittanceControl ***@***.***&gt;
抄送: yaofulan ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [SheldonLoveCoding/KUKA_AdmittanceControl] 代码执行报错 (Issue #2)





 示教板就是和kuka一起出厂生产的控制面板，和机械臂是有线连接的，所有的协作机械臂都有示教板。基于KST连接KUKA你可以从这个连接中找到视频教程。https://www.youtube.com/playlist?list=PLz558OYgHuZd-Gc2-OryITKEXefAmrvae
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 发送日期 | 2024年03月05日 16:07 |
 | 收件人 | SheldonLoveCoding/KUKA_AdmittanceControl ***@***.***&gt; |
 | 抄送人 | SheldonLoveCoding ***@***.***&gt;,
 Comment ***@***.***&gt; |
 | 主题 | Re: [SheldonLoveCoding/KUKA_AdmittanceControl] 代码执行报错 (Issue #2) |
 
 噢噢，谢谢，这个示教板在哪呀
 
 
 
 发自我的iPhone
 
 
 ------------------ 原始邮件 ------------------
 发件人: SheldonLoveCoding ***@***.***&amp;gt;
 发送时间: 2024年3月5日 16:05
 收件人: SheldonLoveCoding/KUKA_AdmittanceControl ***@***.***&amp;gt;
 抄送: yaofulan ***@***.***&amp;gt;, Author ***@***.***&amp;gt;
 主题: Re: [SheldonLoveCoding/KUKA_AdmittanceControl] 代码执行报错 (Issue #2)
 
 
 
 
 
 
 同学你好，机械臂的IP地址需要根据自己的机械臂来修改的。一般来说你可以从KUKA的示教板上找到KUKA的IP地址。

**Comment by yaofulan** [comment]
博主我想再问一下，在速度导纳控制中，eefTarget = eefTarget + eefdTarget(:,i); % 由末端的速度积分得到的末端位置
速度积分得到末端位置，为什么速度没有乘以时间deltaT呢，而是位置和速度直接相加了，后面也有一些地方没有乘以deltaT。另外博主是将这个代码控制真实的机械臂了吗？谢谢解答

**Comment by SheldonLoveCoding** [comment]
你好同学，eefdTarget是提前规划好的，具体来讲的话就是机械臂末端的经过deltaT走过的距离，我注释里写他是速度确实有点不太严谨了，感谢同学指出，但是整个控制逻辑应该没有什么太大问题。


这个代码就是在真实kuka机械臂上做的实验。
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月12日 16:34 |
| 收件人 | SheldonLoveCoding/KUKA_AdmittanceControl ***@***.***> |
| 抄送人 | SheldonLoveCoding ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [SheldonLoveCoding/KUKA_AdmittanceControl] 代码执行报错 (Issue #2) |

博主我想再问一下，在速度导纳控制中，eefTarget = eefTarget + eefdTarget(:,i); % 由末端的速度积分得到的末端位置
速度积分得到末端位置，为什么速度没有乘以时间deltaT呢，而是位置和速度直接相加了，后面也有一些地方没有乘以deltaT。另外博主是将这个代码控制真实的机械臂了吗？谢谢解答

**Comment by yaofulan** [comment]
懂啦，谢谢谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SheldonLoveCoding ***@***.***&gt;
发送时间: 2024年3月12日 16:45
收件人: SheldonLoveCoding/KUKA_AdmittanceControl ***@***.***&gt;
抄送: yaofulan ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [SheldonLoveCoding/KUKA_AdmittanceControl] 代码执行报错 (Issue #2)





 你好同学，eefdTarget是提前规划好的，具体来讲的话就是机械臂末端的经过deltaT走过的距离，我注释里写他是速度确实有点不太严谨了，感谢同学指出，但是整个控制逻辑应该没有什么太大问题。
 
 
 这个代码就是在真实kuka机械臂上做的实验。
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 发送日期 | 2024年03月12日 16:34 |
 | 收件人 | SheldonLoveCoding/KUKA_AdmittanceControl ***@***.***&gt; |
 | 抄送人 | SheldonLoveCoding ***@***.***&gt;,
 Comment ***@***.***&gt; |
 | 主题 | Re: [SheldonLoveCoding/KUKA_AdmittanceControl] 代码执行报错 (Issue #2) |
 
 博主我想再问一下，在速度导纳控制中，eefTarget = eefTarget + eefdTarget(:,i); % 由末端的速度积分得到的末端位置
 速度积分得到末端位置，为什么速度没有乘以时间deltaT呢，而是位置和速度直接相加了，后面也有一些地方没有乘以deltaT。另外博主是将这个代码控制真实的机械臂了吗？谢谢解答
